### ISSUE TITLE
`ActiveFedora::ModelMismatch` error prevents ingest of ETDs

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/etd-loader#7]
Stack trace:

```
ActiveFedora::ModelMismatch: Expected GwEtd. Got: FileSet
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/relation/finder_methods.rb:198:in `class_to_load'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/relation/finder_methods.rb:185:in `load_from_fedora'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/relation/finder_methods.rb:171:in `find_one'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/relation/finder_methods.rb:218:in `find_with_ids'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/relation/finder_methods.rb:48:in `find'
/opt/scholarspace/scholarspace-hyrax/vendor/bundle/ruby/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/querying.rb:3:in `find'
/opt/scholarspace/scholarspace-hyrax/lib/tasks/gwss.rake:135:in `block (2 levels) in <top (required)>'
```

**Comment by kerchner** [comment]
It looks like the minter on the test server is issuing NoIDs that were already issued, hence conflicts like those seen in the stack trace.
